### ISSUE TITLE
[DEP0128] DeprecationWarning: Invalid 'main' field

### ISSUE THREAD

**Issue by suntong** [lpw/command-line-parser#3]
I got this:

```
[DEP0128] DeprecationWarning: Invalid 'main' field in '/app/node_modules/command-line-parser/package.json' of 'command-line-parser.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

when running it under node 16.

**Comment by evanserickson** [comment]
+1 Any options?

**Comment by lpw** [comment]
Fixed

**Comment by mahmoudadel54** [comment]
> Fixed

How ?

**Comment by lpw** [comment]
> > Fixed
> 
> How ?

If you see the latest commit, I simply fixed the ```target``` entry in ```package.json``` to point to the valid entry file ```index.js```

**Comment by successgilli** [comment]
Hi @lpw , there was no version bump for this fix.

**Comment by lpw** [comment]
@successgilli Sorry I missed the version bump (and for the delay) - just bumped the version to 0.2.10 from 0.1.10 .

**Comment by suntong** [comment]
please publish to npm @lpw --

The https://www.npmjs.com/package/command-line-parser still showing latest version being 0.1.10, and so does https://npm.runkit.com/command-line-parser.

Thanks

**Comment by lpw** [comment]
Done, thanks.  -Lance.
